### ISSUE TITLE
undefined method `default_backend=' for Mobility::Configuration

### ISSUE THREAD

**Issue by sedubois** [shioyama/mobility#410]
## Context

When updating Mobility from 0.8.13 to master (2cffe9e6fe8da1d5c443eb2ecad87d64ee182d8c), I get this error on startup:

```
=> Booting Puma
=> Rails 6.0.3.2 application starting in development 
=> Run 'rails server --help` for more startup options
Exiting
Uncaught exception: undefined method 'default_backend=' for #<Mobility::Configuration:0x00007fe7f092fe20>
Did you mean?  default_backend
	/Users/sdubois/Repos/webapp/config/initializers/mobility.rb:4:in 'block in <main>'
	/Users/sdubois/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/bundler/gems/mobility-2cffe9e6fe8d/lib/mobility.rb:185:in 'configure'
	/Users/sdubois/Repos/webapp/config/initializers/mobility.rb:1:in '<main>'
```

The failure happens on the configuration line `config.default_backend = :table` in the initializer (which I did not change).

## Expected Behavior

Application initialization works as before.

## Actual Behavior

Application initialization fails.

## Possible Fix

Appears to be a regression from https://github.com/shioyama/mobility/commit/07a400ec9e27a7c02503028670a42a080676286d#diff-26e809a7ee85d202203e4df2e1098f2cL55 (`attr_accessor :default_backend` was removed).

It might also help to add a non-regression test?

**Comment by shioyama** [comment]
Yeah configuration will change quite a bit in v1.0, that's why I added a note to the readme. I'm trying to maintain rough maps so that simple stuff will still work, but it's not done yet.

I'm going to close this as a known issue (documentation). It's not broken, it's an (undocumented) API change. Thanks for trying master though! I will try to add some info to the wiki soon about how configuration and some other things will work in v1.0 soon.

**Comment by shioyama** [comment]
And you're right: the initializer needs to be updated. And you're right that there should be a test for the initializer so that it stays in sync. Good points! Maybe you could create an issue about having a test that the initializer works?
